### ISSUE TITLE
fails to resolve source files when the filesystem cache is already there

### ISSUE THREAD

**Issue by webdiscus** [webdiscus/html-bundler-webpack-plugin#114] opened 2024-10-20 00:22 UTC
The original issue is here https://github.com/MetaMask/metamask-extension/issues/27831?ysclid=m2gttyzcdn254056696

How to reproduce the issue:

1. `npm webpack watch`
2. stop the process: ctrl+c
3. start new build process (p.1)
4. => display error

**Comment by davidmurdoch** [comment] 2024-11-04 15:36
@webdiscus looks like the recent fix to the filesystem cache caused a new issue when running the config multiple times. The following code errors with:

```console
/home/david/code/metamask-extension/node_modules/webpack/lib/serialization/ObjectMiddleware.js:216
                        throw new Error(
                        ^

Error: ObjectMiddleware.register: serializer for /home/david/code/metamask-extension/node_modules/html-bundler-webpack-plugin/src/Plugin/createPersistentCache.js/PersistentCache is already registered
    at register (/home/david/code/metamask-extension/node_modules/webpack/lib/serialization/ObjectMiddleware.js:216:10)
    at module.exports (/home/david/code/metamask-extension/node_modules/webpack/lib/util/makeSerializable.js:59:2)
    at createPersistentCache (/home/david/code/metamask-extension/node_modules/html-bundler-webpack-plugin/src/Plugin/createPersistentCache.js:29:3)
    at HtmlBundlerPlugin.apply (/home/david/code/metamask-extension/node_modules/html-bundler-webpack-plugin/src/Plugin/AssetCompiler.js:310:31)
    at createCompiler (/home/david/code/metamask-extension/node_modules/webpack/lib/webpack.js:81:12)
    at create (/home/david/code/metamask-extension/node_modules/webpack/lib/webpack.js:154:16)
    at webpack (/home/david/code/metamask-extension/node_modules/webpack/lib/webpack.js:182:32)
    at f (/home/david/code/metamask-extension/node_modules/webpack/lib/index.js:78:21)
    at Object.<anonymous> (/home/david/code/metamask-extension/test.js:17:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)

Node.js v20.11.1
```

Code:

```javascript
const webpack = require('webpack');
const HtmlBundlerPlugin = require('html-bundler-webpack-plugin');

webpack({
  plugins: [
    new HtmlBundlerPlugin()
  ],
  cache: {
    type: 'filesystem',
  }
});

webpack({
  plugins: [
    new HtmlBundlerPlugin()
  ],
  cache: {
    type: 'filesystem',
  }
});```

Save the above as `error.js`, install `webpack` and `html-bundler-webpack-plugin`, then run `node error.js`.

**Comment by webdiscus** [comment] 2024-11-05 08:51
@davidmurdoch thanks for issue report. I will fix it.

**Comment by webdiscus** [comment] 2024-11-05 11:34
@davidmurdoch,

I have fixed the issue when used multiple config and cache `filesystem`, check the `v4.4.1`.

# P.S.

Instead of multiple calling the webpack() function, it should be used multiple config, like:

```js
const webpack = require('webpack');
const HtmlBundlerPlugin = require('html-bundler-webpack-plugin');

webpack([
  {
    name: 'config_1',
    plugins: [new HtmlBundlerPlugin()],
    cache: {
      type: 'filesystem',
    },
  },
  {
    name: 'config_2',
    plugins: [new HtmlBundlerPlugin()],
    cache: {
      type: 'filesystem',
    },
  },
]);
```

**Comment by davidmurdoch** [comment] 2024-11-05 16:38
Thanks! 4.4.1 fixes our tests.

Note: multiple configs isn't feasible in all scenarios. Like in unit tests and other programmatic scenarios where `webpack` might be need to be called multiple times over the life of the Node.js process.

**Comment by webdiscus** [comment] 2024-11-05 18:30
> Note: multiple configs isn't feasible in all scenarios. Like in unit tests and other programmatic scenarios where `webpack` might be need to be called multiple times over the life of the Node.js process.

You are right!
Yes of case the webpack function can be called multiple times, e.g. for test. My tests work exactly like that.

**Comment by webdiscus** [comment] 2024-11-05 18:39
@davidmurdoch thank you for reporting issues! It's very important to me to make the plugin better. My goal is to make this plugin number 1 for Webpack.

Can this issue be closed ?

**Comment by davidmurdoch** [comment] 2024-11-05 21:10
Yes, you can close this one. There _might_ still be some cache issues around the `integrity` option, but I'll just open a new issue if I can reproduce it again.

Thanks!

**Closed** 2024-11-05 21:15 UTC
Labels: bug
