### ISSUE TITLE
[FEATURE REQUEST] Allow to use the `/` as root path to source files

### ISSUE THREAD

**Issue by nathan-barrett** [webdiscus/html-bundler-webpack-plugin#6] opened 2023-03-31 20:58 UTC
## Current behaviour
The CSS, JS and images in my bundled HTML files aren't being output to my output folder, `dist/`

## Expected behaviour
CSS and JS files refrenced in bundled HTML files should be output to the `dist/` folder

### Reproduction Example
My folder structure:

```
├── css
│   ├── _builders-challenge.scss
│   ├── _cohort.scss
│   ├── _footer.scss
│   ├── _innovation-landing.scss
│   ├── _ticker.scss
│   └── style.scss
├── html_output
│   ├── builders-challenge
│   │   └── index.html
│   ├── index.html
│   └── mieco
│       └── index.html
├── scripts
│   ├── analytics.js
│   ├── email.js
│   └── form-utils.js
└── webpack.config.js
```

My webpack config:

```
module.exports = {
  output: {
    path: path.resolve(__dirname, "dist"),
    publicPath: "/",
  },
  plugins: [
    new HtmlBundlerPlugin({
      entry: "./html_output/",
      js: {
        // output filename of extracted JS from source script loaded in HTML via `<script>` tag
        filename: "[name].[contenthash:8].js",
        verbose: true,
      },
      css: {
        // output filename of extracted CSS from source style loaded in HTML via `<link>` tag
        filename: "css/[name].[contenthash:8].css",
        verbose: true,
      },
    }),
```

## Environment

- OS: macOS Ventura 13.1
- version of Node.js: 14.17.6
- version of Webpack: 5.75
- version of the Plugin: 1.12

**Comment by webdiscus** [comment] 2023-03-31 21:11
Hello @nathan-barrett 

thanks for the issue report.
I will research the problem.

**Comment by webdiscus** [comment] 2023-03-31 21:48
@nathan-barrett 

can you please create a small repo with the reproducible issue?
As code base you can use the test case [option-entry-path](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/master/test/cases/option-entry-path).

**Comment by webdiscus** [comment] 2023-04-03 20:03
Hello @nathan-barrett,

I have created the test [issuer-6](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/master/test/cases/issue-6) with a file structure similar to your case. 

I cannot reproduce an issuer. All HTML templates are detected, all assets (styles, scripts, images) was processed and copied into the dist directory.

Please, compare the [issue-6/expected](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/master/test/cases/issue-6/expected) directory (contains same files as `dist`).

Run the test:
```
jest --detectOpenHandles --config ./test/jest.config.js --runTestsByPath ./test/issue.test.js -t='issue-6'
```

**Comment by nathan-barrett** [comment] 2023-04-03 20:29
Thank you! I'll take a look at your example and see if I can reproduce

**Comment by webdiscus** [comment] 2023-04-03 20:59
@nathan-barrett 

ah, I have found the original project here [mozmeao/MIECO](https://github.com/mozmeao/MIECO) ;-)

I see a lot potential for optimization and simplification using the `html-bundler-webpack-plugin`.

I forked this project and will migrate it to the `html-bundler-webpack-plugin`.
In the PR you will see all changes.

**Comment by nathan-barrett** [comment] 2023-04-03 21:11
I made a test repo here, and still getting the same issue here when I'm using absolute paths for imports rather than aliases which you used in the issue-6 folder: 

https://github.com/nathan-barrett/webpack-html-bundle-test

**Comment by webdiscus** [comment] 2023-04-03 22:25
@nathan-barrett 

you will use `root public path` to sources.

Please see the documentation under [loader > options > sources > note](https://github.com/webdiscus/html-bundler-webpack-plugin#sources).

The plugin resolve a relative path or alias.

Url values are not processed:
```
src="https://example.com/img/image.png"
src="//example.com/img/image.png"
src="/img/image.png"
```

Reason: to distinguish the path to the source file that should be processed from the URL in the public path (is already in the output path). Because in some case you can have all images already in public path and define an image with `root public`, e.g.: `<img src="/img/image.png">` <= this is root public path (in `dist` directory). In this case this is root URL, not root path to src directory.

Why don't you want to use Webpack aliases? It is same as root path. You can define one alias as the root path, e.g.:
```js
resolve: {
    alias: {
      '@': path.join(__dirname),
    },
  },
```

And you can use the `@` alias as `root` path:
```html
<html>
<head>
    <title>home</title>

    <!-- load global style -->
    <link href="@/css/style.scss" rel="stylesheet">

    <!-- load global script -->
    <script src="@/scripts/main.js" defer="defer"></script>
</head>
<body>
    <img src="@/img/placeholder.png">
</body>
</html>
```

Yes, of cause, I can add the new option, e.g. `root` or `basedir` to enable using the `/` root path as path to sources instead of currently `root public path` in `dist` directory.

What do you like:
1 - use '@' Webpack alias as `root` path
2 - define extra one option? If yes, what should be the option name:  `root` (like by many template engines) or `basedir`? (defaults will be always false for compatibility)

Then the config will look like this:
```js
   new HtmlBundlerPlugin({
      entry: './html_output/',
      js: {
        filename: '[name].[contenthash:8].js',
      },
      css: {
        filename: 'css/[name].[contenthash:8].css',
      },
      loaderOptions: {
        // enable to use the '/' as path to source directory for assets
        root: path.join(__dirname), // <= this is just a suggestion, still needs to be implemented
      },
    }),
```

**Comment by nathan-barrett** [comment] 2023-04-03 22:40
I personally prefer the `root` option under `loaderOptions` but both options work. My hesitation on using webpack aliases is just that it would be a different pattern to use than how the rest of our projects operate. Really appreciate you taking a look into this!

**Comment by webdiscus** [comment] 2023-04-03 22:43
Yes, it make sense to add new `root` option. I will implement it.

**Comment by webdiscus** [comment] 2023-04-04 13:52
@nathan-barrett 

in the new `1.14.0` version I have added the `root` loader option.
See please the documentation for the [root](https://github.com/webdiscus/html-bundler-webpack-plugin#root) option.

**Comment by webdiscus** [comment] 2023-04-04 22:11
Hello @nathan-barrett 

can you please check my [PR](https://github.com/mozmeao/MIECO/pull/40) in the `mozmeao/MIECO` repository?

**Comment by nathan-barrett** [comment] 2023-04-05 01:19
Yeah, thanks. I'll be sure to look

**Comment by webdiscus** [comment] 2023-04-19 19:17
@nathan-barrett 

I close the issue as done, because this feature already works in the merged [PR](https://github.com/mozmeao/MIECO/pull/40).

**Closed by webdiscus** 2023-04-19 19:17 UTC
Labels: enhancement
